# -*- coding: utf-8 -*-
"""Project1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1djzkYPaprvx-xXJvlMsmJ5y37BJ7yMT-
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

data = pd.read_csv('healing_col.csv')
data.columns
heal_times = data.loc[::3, 'heal']
nonheal_times = data.loc[::3, 'nonheal']
avgheal = heal_times.mean()
avgnonheal = nonheal_times.mean()

display(avgheal)
display(avgnonheal)
stats.ttest_ind(heal_times,nonheal_times)

data2 = [heal_times, nonheal_times]
fig = plt.figure(figsize =(7, 5))
ax = fig.add_axes([0, 0, 1, 1])
bp = ax.boxplot(data2, patch_artist = True,
                notch ='True', vert = 0)
plt.title('Wound Healing Rate for Different Bacteria', size = 25)
plt.xlabel('Hours to Normal', size=20)


#Making it Look Nicer  
colors = ['green', 'lightskyblue']
  
for patch, color in zip(bp['boxes'], colors):
    patch.set_facecolor(color)
  
# changing color and linewidth of
# whiskers
for whisker in bp['whiskers']:
    whisker.set(color ='dimgray',
                linewidth = 3,
                linestyle =":")
  
# changing color and linewidth of caps
for cap in bp['caps']:
    cap.set(color ='dimgray',
            linewidth = 3)
  
# changing color and linewidth of medians
for median in bp['medians']:
    median.set(color ='crimson',
               linewidth = 3)
  
# changing style of fliers
for flier in bp['fliers']:
    flier.set(marker ='D',
              color ='#e7298a',
              alpha = 0.5)
      
# x-axis labels
ax.set_yticklabels(['Nonaggressive', 'Aggressive'], size = 15)